name: the protector.
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  dumbci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Clean
        run: pnpm clean
      - name: Install
        run: pnpm install
      - name: Lint
        run: pnpm lint
      - name: Generate Types
        run: pnpm db:gen
      - name: Test
        run: pnpm test
      - name: Build
        run: pnpm build
