name: the protector.
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  dumbci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Information"
        run: |
          echo "OS: $(uname -a)"
          echo "Node Environment: $(node -e "console.log(process.env.NODE_ENV)")"
          echo "Node Version: $(node -v)"
          echo "NPM Version: $(npm -v)"
          echo "PNPM Version: $(pnpm -v)"
      - name: Install
        run: pnpm install
      - name: Lint
        run: pnpm lint
      - name: Generate Types
        run: pnpm db:gen
      - name: Test
        run: pnpm test
      - name: Build
        run: pnpm build
