name: the protector.
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    environment: preview
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 19.7.0

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 8.2.0

      - name: Setup Vercel CLI
        run: |
          pnpm install -g vercel@canary

      - name: "Information"
        run: |
          echo "OS: $(uname -a)"
          echo "Node Version: $(node -v)"
          echo "NPM Version: $(npm -v)"
          echo "PNPM Version: $(pnpm -v)"

      - name: Install
        run: pnpm install

      - name: Lint
        run: pnpm lint

      - name: Generate Types
        run: pnpm db:gen

      - name: Build
        run: |
          vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_AUTH }}
          vercel build --token=${{ secrets.VERCEL_AUTH }}
          vercel deploy --prebuilt --token=${{ secrets.VERCEL_AUTH }}
  deploy-production:
  runs-on: ubuntu-latest
  needs: deploy-preview
  environment: production
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Deploy Preview
      run: |
        vercel pull --yes --environment=production --token=${{ secrets.VERCEL_AUTH }}
        vercel build --prod --token=${{ secrets.VERCEL_AUTH }}
        vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_AUTH }}
