name: the protector.
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  dumbci:
    runs-on: ubuntu-latest
    environment: preview
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 8.2.0

      - name: "Information"
        run: |
          echo "OS: $(uname -a)"
          echo "Node Version: $(node -v)"
          echo "NPM Version: $(npm -v)"
          echo "PNPM Version: $(pnpm -v)"

      - name: Install
        run: pnpm install

      - name: Lint
        run: pnpm lint

      # Vercel does the build for us, so it'd be stupid to build & clean here. : )
